server:
  port: 8080

spring:
  redis:
    host: 47.100.98.247
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数
        min-idle: 0 #最小空闲数量
        max-idle: 4 #最大空闲熟练
        max-wait: 1ms #阻塞时长